### ISSUE TITLE
Building an iOS Swift static framework that depends on an objc_library

### ISSUE THREAD

**Issue by ghost** [ios-bazel-users/ios-bazel-users#18]
Hi @keith 
Was looking into your implementation for `prebuilt_swift_static_framework` and wanted to try building a static framework for a `swift_library` that has a dependency on an `objc_library`:

```
prebuilt_swift_static_framework(
    name = "Whatever",
    srcs = glob(["path/to/sources/*.swift"]),
    deps = [":SomeObjCLibraryDep"],
)
```

It appears that in order to make that work, the module map information from each `objc_library` dependency needs to be bundled. I think you can get that information from the `apple_common.Objc` but not sure where that information needs to be passed when generating the framework. Perhaps they should be passed to the `ctx.actions.run` [inputs](https://github.com/ios-bazel-users/ios-bazel-users/blob/master/prebuilt_swift_static_framework/prebuilt_swift_static_framework.bzl#L47) and to [arguments](https://github.com/ios-bazel-users/ios-bazel-users/blob/master/prebuilt_swift_static_framework/prebuilt_swift_static_framework.bzl#L52) so they are included in the fat file?

Also, where does [archive](https://github.com/ios-bazel-users/ios-bazel-users/blob/master/prebuilt_swift_static_framework/prebuilt_swift_static_framework.bzl#L34) come from? 

Thank you!

**Comment by keith** [comment]
There are a few ways you could probably go about this:

You could try and do what you're implying and bundle the objc_library files into the final framework (and also the symbols into the final static archive similar to `ios_static_framework`). To do this you would probably do what you mentioned and read the details of the objc_library from the Objc provider

Alternatively you could vendor the frameworks separately, and expect consumers to add both of them. This may not work for you depending on your use case, but if you created an `ios_static_framework` for the `objc_library` you could get a separate framework that wrapped that library, and then consumers could depend on both, which should work correctly at link time.

Either way this probably isn't something we're going to add to our example, because in our case we're doing the latter, and including many precompiled frameworks in our build. But if you'd like to submit a backwards compatible change, or a new example rule here, that would be fine with me!

> Also, where does archive come from?

rules_swift propagates a CcInfo provider https://github.com/bazelbuild/rules_swift/blob/5933dae72ccebefd47f03db3c5a1476b681e81d9/swift/internal/swift_library.bzl#L124-L130 which bazel turns into a library internally. You can see docs on that provider here https://docs.bazel.build/versions/master/skylark/lib/CcInfo.html

**Comment by ghost** [comment]
Thank you for the quick reply! I think using the vendor frameworks approach is cleaner/simpler and will work for my use case. 

Regarding the `archive` variable, I was trying to determine where it's declared.  When I try to build, I get `name 'archive' is not defined`. To resolve, I use `deps[0][CcInfo]`.

**Comment by keith** [comment]
Ah, I missed some updates last time, https://github.com/ios-bazel-users/ios-bazel-users/pull/19

**Comment by ghost** [comment]
No problem at all! Left a couple of comments in the PR, but seems to be working for me. Thank you for your help!
