### ISSUE TITLE
Best strategy to use to record snapshot tests?

### ISSUE THREAD

**Issue by tinder-maxwellelliott** [ios-bazel-users/ios-bazel-users#39]
Hello All,

What is the best approach for adopting recordable snapshot tests? I know that the test runner environment provides some special file-paths (`TMP_UNDECLARED_OUTPUTS`) that can be written to, are you writing to those paths and then unpacking the zipped test bundle to extract the newly recorded snapshots? 

Thanks

**Comment by keith** [comment]
We pass an env var like `SNAPSHOT_ARTIFACTS`. You can do this with `--test_env=SNAPSHOT_ARTIFACTS=/some/path`. Right now we don't check in snapshots so that's kinda where our integration ends but I imagine we could take those from the script that runs the tests and do the cp afterwards outside of bazel and it would work well.

**Comment by tinder-maxwellelliott** [comment]
Thanks! I will look into the `cp` approach!
